#!/usr/bin/env python3
#
# Based on https://github.com/grundic/zabbix-disk-performance/blob/master/lld-disks.py

import json
import subprocess

if __name__ == '__main__':
    mysql_show_databases = subprocess.run(
            [ "mysql", "-B", "--skip-column-names", "-e", "show databases" ],
            capture_output=True, text=True, check=True)
    data = list()
    for line in mysql_show_databases.stdout.splitlines():
        if line and "lost+found" not in line:
            data.append({"{#DATABASE}": line})

    print(json.dumps({"data": data}, indent=4))
