#!/usr/bin/env python
#
# Based on https://github.com/grundic/zabbix-disk-performance/blob/master/lld-disks.py

import json
import subprocess

if __name__ == '__main__':
    process = subprocess.Popen("echo 'show databases'|mysql -B --skip-column-names", shell=True, stdout=subprocess.PIPE)
    output = process.communicate()[0]
    data = list()
    for line in output.split("\n"):
        if line:
	    database = line
            data.append({"{#DATABASE}": line})

    print(json.dumps({"data": data}, indent=4))
