#!/usr/bin/env python3
#
# Based on https://github.com/grundic/zabbix-disk-performance/blob/master/lld-disks.py

import json
import subprocess

if __name__ == '__main__':
    process = subprocess.run("echo 'show databases'|mysql -B --skip-column-names|grep -v 'lost+found'", capture_output=True, shell=True, encoding='utf8')
    lines = process.stdout.splitlines()
    data = list()
    for line in lines:
        if line:
            database = line
            data.append({"{#DATABASE}": line})

    print(json.dumps({"data": data}, indent=4))

